#server configuration
server:
  port: 8081
spring:
  application:
    name: kodBook-service
  profiles:
    active: DEV
  output:
    ansi:
      enabled: always
info:
  app:
    name: KodBook
    version: 1.0.0
    description: kodBook service
  author:
    name: J Hareesh Kumar