#Dev profile configuration
spring:
  #Devtools configuration
  devtools:
    add-properties: true
  #Bootstrap spring data jpa configuration
  data:
    jpa:
      repositories:
        bootstrap-mode: strict
  #Database configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # SendGrid configuration
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
#logging configuration
logging:
  level:
    root: info
    web: debug
    security: debug
  file:
    name: logs/dev.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#Actuator configuration
management:
  server:
    port: 8082
  endpoints:
    web:
      exposure:
        include: "*"
    info:
      env:
        enabled: true
    security:
      enabled: true
    endpoint:
      health:
        show-details: always
      info:
        enabled: true