#prod profile configuration
spring:
  #Database configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  # SendGrid configuration
  sendgrid:
    api-key: ${SENDGRID_API_KEY}