#Dev profile configuration
spring:
  #Devtools configuration
  devtools:
    add-properties: true
  #Bootstrap spring data jpa configuration
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  #Database configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
  # SendGrid configuration
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
#logging configuration
logging:
  level:
    root: info
    web: debug
    security: debug
  logback:
    rollingpolicy:
      file-name-pattern: var/log/${spring.application.name}.dev.%d{yyyy-MM-dd}.%i.gz
      max-file-size: 1KB
      max-history: 7
#Actuator configuration
management:
  server:
    port: 8082
  endpoints:
    web:
      exposure:
        include: "*"
    info:
      env:
        enabled: true
    security:
      enabled: true
    endpoint:
      health:
        show-details: always
      info:
        enabled: true
#springdoc - openApi(Swagger UI)
springdoc:
  swagger-ui:
    filter: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  show-actuator: true
  writer-with-default-pretty-printer: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  cache:
    disabled: true