#prod profile configuration
spring:
  #Devtools configuration
  devtools:
    add-properties: false
    livereload:
      enabled: false
  #Bootstrap spring data jpa configuration
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy
  #Database configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
  # SendGrid configuration
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
  #SBA configuration
  boot:
    admin:
      client:
        auto-registration: true
        url: ${SBA_SERVER_URL}
        username: ${SBA_SERVER_USERNAME}
        password: ${SBA_SERVER_PASSWORD}
        instance:
          metadata:
            user.name: ${SBA_CLIENT_ACTUATOR_USERNAME}
            user.password: ${SBA_CLIENT_ACTUATOR_PASSWORD}
          service-base-url: ${SBA_CLIENT_BASE_URL}
server:
  forward-headers-strategy: native
#logging configuration
logging:
  level:
    root: info
  structured:
    format:
      #      console: ecs
      file: ecs
  file:
    name: var/log/${spring.application.name}.log
  #  pattern:
  #    console: "%d{mm} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log.gz
      max-file-size: 10MB
      max-history: 7

#Actuator configuration
management:
  info:
    os:
      enabled: true
    java:
      enabled: true
    build:
      enabled: true
    env:
      enabled: true
    git:
      mode: simple
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
    env:
      show-values: never

#springdoc - openApi(Swagger UI)
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}